<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>pvaify</artifactId>
  <parent>
    <groupId>org.phoebus</groupId>
    <artifactId>parent</artifactId>
    <version>5.0.5</version>
  </parent>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.phoebus</groupId>
      <artifactId>core-pva</artifactId>
      <version>5.0.5</version>
    </dependency>
    <dependency>
      <groupId>org.phoebus</groupId>
      <artifactId>core-pv</artifactId>
      <version>5.0.5</version>
    </dependency>
    <dependency>
      <groupId>org.phoebus</groupId>
      <artifactId>core-pv-ca</artifactId>
      <version>5.0.5</version>
      <exclusions>
        <!-- trim epics-core -->
        <exclusion>
          <groupId>org.epics</groupId>
          <artifactId>epics-pvdata</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.epics</groupId>
          <artifactId>epics-pvaccess</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.epics</groupId>
          <artifactId>epics-ntypes</artifactId>
        </exclusion>
      </exclusions> 
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <!-- Copy dependencies into target/lib -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
              <overWriteReleases>false</overWriteReleases>
              <overWriteSnapshots>false</overWriteSnapshots>
              <overWriteIfNewer>true</overWriteIfNewer>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <!-- Build executable JAR -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
              <mainClass>org.phoebus.pvaify.Main</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
